#ifndef HF_FUNCTIONS_H_
#define HF_FUNCTIONS_H_


typedef enum{
	HF_FUNCTION_RETURN_OK,
	HF_FUNCTION_RETURN_BUFFER_EMPTY,
	HF_FUNCTION_RETURN_ERROR
}HF_FUNCTION_RETURN_STATE;


typedef enum{
	HF_INTERRUPTION_EDGE_RSING,
	HF_INTERRUPTION_EDGE_FALLING,
}HF_INTERRUPTION_EDGE_TYPE;

#endif /* HF_FUNCTIONS_H_ */
